name: equibind
channels:
  - conda-forge
  - defaults
  - dglteam
  - pytorch
dependencies:
  - python=3.7
  - pytorch=1.9.0
  - torchvision
  - cudatoolkit=11.1
  - torchaudio
  - dgl-cuda11.1
  - rdkit
  - openbabel
  - biopython
  - rdkit
  - biopandas
  - pot
  - dgllife
  - joblib
  - pyaml
  - icecream
  - matplotlib
  - tensorboard



